#server:
#  port: 8080 //8080 is bydefault

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username : root
    password : Harish@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
